arduino_lab_p/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from errors.errors_view import (
    handler404,
    handler403,
    handler500,
    handler400,
)  # Import the error handlers

from products.sitemaps import MicrocontrollerSitemap, StaticViewSitemap

# Define the sitemaps dictionary
sitemaps = {
    "microcontrollers": MicrocontrollerSitemap,
    "static": StaticViewSitemap,
}

urlpatterns = [
    path("", include("home.urls")),  # Include URLs from home app
    path("admin/", admin.site.urls),  # Admin site
    path("accounts/", include("allauth.urls")),  # Authentication (allauth)
    path("products/", include("products.urls")),  # Product app URLs
    path("bag/", include("bag.urls")),  # Shopping bag app URLs
    path("checkout/", include("checkout.urls")),  # Checkout process
    path("profile/", include("profiles.urls")),  # User profile URLs
    path("store_settings/", include("store_settings.urls")),  # Store settings 
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),  # Sitemap URL
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)  # Serving media files
urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)  # Serving static files

# Register the error handlers
handler404 = "errors.errors_view.handler404"
handler403 = "errors.errors_view.handler403"
handler500 = "errors.errors_view.handler500"
handler400 = "errors.errors_view.handler400"

bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.view_bag, name="view_bag"),
    path("add/<item_id>/", views.add_to_bag, name="add_to_bag"),
    path("adjust/<item_id>/", views.adjust_bag, name="adjust_bag"),
    path("remove/<item_id>/", views.remove_from_bag, name="remove_from_bag"),
]

store_settings/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(
        "settings/", views.settings_view, name="settings"
    ),  # URL for the settings page
    path("change_password/", views.change_password, name="change_password"),
    path("toggle-newsletter/", views.toggle_newsletter, 
         name="toggle_newsletter"),
]

store_settings/models.py
from django.db import models
from django.contrib.auth.models import User


class StoreSettings(models.Model):
    """General store settings."""

    store_name = models.CharField(max_length=255)
    store_description = models.TextField()
    contact_email = models.EmailField()
    currency = models.CharField(max_length=10, default="EUR")

    def __str__(self):
        return self.store_name


class PaymentSettings(models.Model):
    """Payment settings related to store."""

    store = models.ForeignKey(
        StoreSettings, on_delete=models.CASCADE,
          related_name="payment_settings"
    )
    stripe_public_key = models.CharField(max_length=255, blank=True)
    stripe_secret_key = models.CharField(max_length=255, blank=True)
    paypal_client_id = models.CharField(max_length=255, blank=True)
    paypal_client_secret = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return f"Payment settings for {self.store.store_name}"


class ShippingSettings(models.Model):
    """Shipping settings related to store."""

    store = models.ForeignKey(
        StoreSettings, on_delete=models.CASCADE,
          related_name="shipping_settings"
    )
    standard_shipping_cost = models.DecimalField(
        max_digits=6, decimal_places=2, default=5.00
    )
    free_shipping_threshold = models.DecimalField(
        max_digits=6, decimal_places=2, default=50.00
    )

    def __str__(self):
        return f"Shipping settings for {self.store.store_name}"


class UserSettings(models.Model):
    """User-specific settings."""

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    preferred_language = models.CharField(max_length=50, default="en")
    receive_newsletter = models.BooleanField(
        default=True
    )  # Flag pentru înscrierea la newsletter

    def __str__(self):
        return self.user.username

store_settings/forms.py
from .models import UserSettings
from django import forms
from .models import (
    StoreSettings, PaymentSettings, ShippingSettings, UserSettings)


class StoreSettingsForm(forms.ModelForm):
    """Form for updating store settings."""

    class Meta:
        model = StoreSettings
        fields = ["store_name", "store_description",
                  "contact_email", "currency"]
        widgets = {
            # Controlează dimensiunea
            "store_description": forms.Textarea(attrs={"rows": 1, "cols": 40}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = False  # Make all fields optional


class PaymentSettingsForm(forms.ModelForm):
    """Form for updating payment settings."""

    class Meta:
        model = PaymentSettings
        fields = [
            "stripe_public_key",
            "stripe_secret_key",
            "paypal_client_id",
            "paypal_client_secret",
        ]
        widgets = {
            "stripe_secret_key": forms.PasswordInput(render_value=True),
            "paypal_client_secret": forms.PasswordInput(render_value=True),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = False  # Make all fields optional


class ShippingSettingsForm(forms.ModelForm):
    """Form for updating shipping settings."""

    class Meta:
        model = ShippingSettings
        fields = ["standard_shipping_cost", "free_shipping_threshold"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = False  # Make all fields optional


class UserSettingsForm(forms.ModelForm):
    """Form for updating user-specific settings."""

    class Meta:
        model = UserSettings
        fields = ["preferred_language", "receive_newsletter"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = False  # Make all fields optional


# store_settings/forms.py


class NewsletterForm(forms.ModelForm):
    class Meta:
        model = UserSettings
        fields = ["receive_newsletter"]
        labels = {"receive_newsletter": "Subscribe to our newsletter"}
        widgets = {
            "receive_newsletter": forms.CheckboxInput(
                attrs={"class": "toggle-checkbox"}
            ),
        }

store_settings/views.py
from .models import UserSettings  # Asigură-te că ai modelul UserSettings
from django.contrib.messages import get_messages
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.http import JsonResponse
from .models import UserSettings
from django.conf import settings
from .forms import NewsletterForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import StoreSettings, PaymentSettings, ShippingSettings, UserSettings
from .forms import (
    StoreSettingsForm,
    PaymentSettingsForm,
    ShippingSettingsForm,
    UserSettingsForm,
)


@login_required
def settings_view(request):
    """A view to return and update the settings page for superusers."""

    # Ensure store settings exist or create new one
    store_settings, _ = StoreSettings.objects.get_or_create(
        id=1
    )  # Assuming there's always a single StoreSettings

    # Ensure payment and shipping settings are linked to store settings
    payment_settings, _ = PaymentSettings.objects.get_or_create(
        store=store_settings)
    shipping_settings, _ = ShippingSettings.objects.get_or_create(
        store=store_settings)

    # Get the user's settings, or create them if they don't exist
    user_settings, _ = UserSettings.objects.get_or_create(user=request.user)

    if request.method == "POST":
        # Bind POST data to the forms
        store_form = StoreSettingsForm(request.POST, instance=store_settings)
        payment_form = PaymentSettingsForm(
            request.POST, instance=payment_settings)
        shipping_form = ShippingSettingsForm(
            request.POST, instance=shipping_settings)
        user_settings_form = UserSettingsForm(
            request.POST, instance=user_settings)

        # Validate all forms
        if (
            store_form.is_valid()
            and payment_form.is_valid()
            and shipping_form.is_valid()
            and user_settings_form.is_valid()
        ):
            # Save store settings
            store_form.save()

            # Ensure the store is linked to payment and shipping settings
            payment_settings = payment_form.save(commit=False)
            payment_settings.store = store_settings
            payment_settings.save()

            shipping_settings = shipping_form.save(commit=False)
            shipping_settings.store = store_settings
            shipping_settings.save()

            # Save user settings
            user_settings_form.save()

            # Show success message
            messages.success(request, "Settings updated successfully!")
            # Redirect back to the home page after saving
            return redirect("home")
        else:
            # If any forms are invalid, display error message
            messages.error(request, "Please correct the errors in the forms.")
    else:
        # Initialize forms with current instance data
        store_form = StoreSettingsForm(instance=store_settings)
        payment_form = PaymentSettingsForm(instance=payment_settings)
        shipping_form = ShippingSettingsForm(instance=shipping_settings)
        user_settings_form = UserSettingsForm(instance=user_settings)

    # Pass forms to template context
    context = {
        "store_form": store_form,
        "payment_form": payment_form,
        "shipping_form": shipping_form,
        # Include user settings form in the context
        "user_settings_form": user_settings_form,
    }

    return render(request, "store_settings/settings.html", context)


def change_password(request):
    """A view to change the user's password."""
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            # Prevent user from being logged out
            update_session_auth_hash(request, user)
            messages.success(request, "Password changed successfully!")
            # Redirect back to the home page after changing password
            return redirect("settings")
        else:
            messages.error(request, "Please correct the errors in the form.")
    else:
        form = PasswordChangeForm(request.user)
    return render(request, "store_settings/change_password.html", {"form": form})


# store_settings/views.py


@login_required
def toggle_newsletter(request):
    """Permite utilizatorilor să se aboneze sau să se dezaboneze de la
    newsletter."""
    msg = render_to_string(
        "store_settings/newsletter_subscribe_confirmation.txt",
        {"user_email": request.user.email},
    )
    if request.method == "POST":
        # Obține sau creează setările utilizatorului
        user_settings, created = UserSettings.objects.get_or_create(
            user=request.user)

        # Toggle pentru starea abonamentului
        user_settings.receive_newsletter = (
            not user_settings.receive_newsletter)
        user_settings.save()

        # Mesaj în funcție de noua stare
        if user_settings.receive_newsletter:
            messages.success(request, msg)
            send_mail(
                "ArduinoLab Subscribe",
                msg,
                settings.DEFAULT_FROM_EMAIL,
                [request.user.email],
            )

        else:
            msg = render_to_string(
                "store_settings/newsletter_unsubscribe_confirmation.txt",
                {"user_email": request.user.email},
            )
            messages.info(request, msg)
            send_mail(
                "ArduinoLab Subscribe",
                msg,
                settings.DEFAULT_FROM_EMAIL,
                [request.user.email],
            )

        return JsonResponse(
            {"status": "success", "subscribed": (
                user_settings.receive_newsletter)}
        )

    return JsonResponse({"status": "error"}, status=400)

store_settings/templates/store_settings/change_password.html
{% extends "base.html" %}
{% load static %}

{% load widget_tweaks %}
{% load static %}

{% block content %}
{% block free_delivery %}
{% endblock %}

<div class="container settings-container mt-5">
    <h1>Change Password Settings</h1>
    <form method="POST">
        {% csrf_token %}
        
        <!-- Afișează fiecare câmp individual -->
        <div class="form-group">
            <label for="id_old_password">Old Password</label>
            {{ form.old_password|add_class:"form-control" }}
            <input type="checkbox" onclick="togglePassword('id_old_password')" /> Show Password
        </div>

        <div class="form-group">
            <label for="id_new_password1">New Password</label>
            {{ form.new_password1|add_class:"form-control" }}
            <input type="checkbox" onclick="togglePassword('id_new_password1')" /> Show Password
        </div>

        <div class="form-group">
            <label for="id_new_password2">Confirm New Password</label>
            {{ form.new_password2|add_class:"form-control" }}
            <input type="checkbox" onclick="togglePassword('id_new_password2')" /> Show Password
        </div>

        <button type="submit" class="btn btn-primary">Save Settings</button>
        <button type="button" class="btn btn-secondary" onclick="window.location.href='{% url 'settings' %}'">Cancel</button>
    </form>
</div>

<script>
function togglePassword(fieldId) {
    var field = document.getElementById(fieldId);
    if (field.type === "password") {
        field.type = "text";
    } else {
        field.type = "password";
    }
}
</script>
{% block footer %}

{% endblock %}
{% endblock %}

store_settings/templates/store_settings/settings.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page_header %}
    <div class="container pt-5">
  
    </div>
{% endblock %}
{% block content %}
{% block free_delivery %}
{% endblock %}
<div class="container mt-5 pt-5">  <!-- Added pt-5 to create space under the fixed header -->
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-sm-12">
            <div class="card bg-light shadow-lg" style="opacity: 0.9;">
                <div class="card-body">
                    <h1 class="text-center">Store Settings</h1>
                    <form method="POST" class="mt-4 form-horizontal">
                        {% csrf_token %}
                        {% if request.user.is_superuser %}
                        <h2 class="h4">General Store Settings</h2>
                        <div class="form-group row mb-3">
                            <label for="id_store_name" class="col-sm-3 col-form-label text-end">Store Name</label>
                            <div class="col-sm-9">
                                {{ store_form.store_name|add_class:"form-control" }}
                            </div>
                        </div>
                        <div class="form-group row mb-3">
                            <label for="id_store_description" class="col-sm-3 col-form-label text-end">Store Description</label>
                            <div class="col-sm-9">
                                {{ store_form.store_description|add_class:"form-control" }}
                            </div>
                        </div>
                        <div class="form-group row mb-3">
                            <label for="id_contact_email" class="col-sm-3 col-form-label text-end">Contact Email</label>
                            <div class="col-sm-9">
                                {{ store_form.contact_email|add_class:"form-control" }}
                            </div>
                        </div>
                        <div class="form-group row mb-3">
                            <label for="id_currency" class="col-sm-3 col-form-label text-end">Currency</label>
                            <div class="col-sm-9">
                                {{ store_form.currency|add_class:"form-control" }}
                            </div>
                        </div>

                        <h2 class="h4 mt-4">Payment Settings</h2>
                        <div class="form-group row mb-3">
                            <label for="id_stripe_public_key" class="col-sm-3 col-form-label text-end">Stripe Public Key</label>
                            <div class="col-sm-9">
                                {{ payment_form.stripe_public_key|add_class:"form-control" }}
                            </div>
                        </div>
                        <div class="form-group row mb-3">
                            <label for="id_stripe_secret_key" class="col-sm-3 col-form-label text-end">Stripe Secret Key</label>
                            <div class="col-sm-9">
                                {{ payment_form.stripe_secret_key|add_class:"form-control" }}
                                <input type="checkbox" onclick="togglePassword('id_stripe_secret_key')"> Show Password
                            </div>
                        </div>
                        <div class="form-group row mb-3">
                            <label for="id_paypal_client_id" class="col-sm-3 col-form-label text-end">Paypal Client ID</label>
                            <div class="col-sm-9">
                                {{ payment_form.paypal_client_id|add_class:"form-control" }}
                            </div>
                        </div>
                        <div class="form-group row mb-3">
                            <label for="id_paypal_client_secret" class="col-sm-3 col-form-label text-end">Paypal Client Secret</label>
                            <div class="col-sm-9">
                                {{ payment_form.paypal_client_secret|add_class:"form-control" }}
                                <input type="checkbox" onclick="togglePassword('id_paypal_client_secret')"> Show Password
                            </div>
                        </div>

                        <h2 class="h4 mt-4">Shipping Settings</h2>
                        <div class="form-group row mb-3">
                            <label for="id_standard_shipping_cost" class="col-sm-3 col-form-label text-end">Standard Shipping Cost</label>
                            <div class="col-sm-9">
                                {{ shipping_form.standard_shipping_cost|add_class:"form-control" }}
                            </div>
                        </div>
                        <div class="form-group row mb-3">
                            <label for="id_free_shipping_threshold" class="col-sm-3 col-form-label text-end">Free Shipping Threshold</label>
                            <div class="col-sm-9">
                                {{ shipping_form.free_shipping_threshold|add_class:"form-control" }}
                            </div>
                        </div>
                        {% endif %}

                        <h2 class="h4 mt-4 ">User Settings</h2>
                        <div class="form-group row mb-3">
                            <label for="id_preferred_language" class="col-sm-3 col-form-label text-end">Preferred Language</label>
                            <div class="col-sm-9">
                                {{ user_settings_form.preferred_language|add_class:"form-control" }}
                            </div>
                        </div>
                        <div class="form-group row mb-3 ">
                            <label for="id_receive_newsletter" class="col-sm-3 col-form-label text-end">Receive Newsletter</label>
                            <div class="col-sm-9 " >
                                {{ user_settings_form.receive_newsletter|add_class:"form-control" }}
                            </div>
                        </div>

                        <div class="form-group row mb-3">
                            <div class="col-sm-9 offset-sm-3">
                                <a href="{% url 'change_password' %}" class="btn btn-warning mb-3">Change Password</a>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-9 offset-sm-3">
                                <button type="submit" class="btn btn-primary">Save Settings</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- JavaScript pentru a face toggle pe parole -->
<script>
function togglePassword(fieldId) {
    var field = document.getElementById(fieldId);
    if (field.type === "password") {
        field.type = "text";
    } else {
        field.type = "password";
    }
}
</script>
{% block footer %}

{% endblock %}

{% endblock %}