arduino_lab_p/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from errors.errors_view import (
    handler404,
    handler403,
    handler500,
    handler400,
)  # Import the error handlers

from products.sitemaps import MicrocontrollerSitemap, StaticViewSitemap

# Define the sitemaps dictionary
sitemaps = {
    "microcontrollers": MicrocontrollerSitemap,
    "static": StaticViewSitemap,
}

urlpatterns = [
    path("", include("home.urls")),  # Include URLs from home app
    path("admin/", admin.site.urls),  # Admin site
    path("accounts/", include("allauth.urls")),  # Authentication (allauth)
    path("products/", include("products.urls")),  # Product app URLs
    path("bag/", include("bag.urls")),  # Shopping bag app URLs
    path("checkout/", include("checkout.urls")),  # Checkout process
    path("profile/", include("profiles.urls")),  # User profile URLs
    path("store_settings/", include("store_settings.urls")),  # Store settings 
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),  # Sitemap URL
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)  # Serving media files
urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)  # Serving static files

# Register the error handlers
handler404 = "errors.errors_view.handler404"
handler403 = "errors.errors_view.handler403"
handler500 = "errors.errors_view.handler500"
handler400 = "errors.errors_view.handler400"

bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.view_bag, name="view_bag"),
    path("add/<item_id>/", views.add_to_bag, name="add_to_bag"),
    path("adjust/<item_id>/", views.adjust_bag, name="adjust_bag"),
    path("remove/<item_id>/", views.remove_from_bag, name="remove_from_bag"),
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # List all microcontrollers
    path("microcontrollers/", views.all_microcontrollers,
          name="all_microcontrollers"),
    # View details of a specific microcontroller
    path(
        "microcontroller/<int:microcontroller_id>/",
        views.microcontroller_detail,
        name="microcontroller_detail",
    ),
    # Add a new microcontroller
    path("add-microcontroller/", views.add_microcontroller,
          name="add_microcontroller"),
    # Edit an existing microcontroller
    path(
        "edit-microcontroller/<int:microcontroller_id>/",
        views.edit_microcontroller,
        name="edit_microcontroller",
    ),
    # Delete a microcontroller
    path(
        "delete-microcontroller/<int:microcontroller_id>/",
        views.delete_microcontroller,
        name="delete_microcontroller",
    ),
]

checkout/models.py
import uuid
from django.db import models
from django.db.models import Sum
from django.conf import settings
from store_settings.context_processors import get_shipping_settings
from django_countries.fields import CountryField
from products.models import Microcontroller
from profiles.models import UserProfile


class Order(models.Model):
    """Model for Orders"""
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(
        UserProfile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="orders",
    )
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label="Country *", null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0
    )
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0
    )
    grand_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0
    )
    original_bag = models.TextField(null=False, blank=False, default="")
    stripe_pid = models.CharField(
        max_length=254,
        null=False,
        blank=False,
        default=""
    )

    def _generate_order_number(self):
        """Generate a random, unique order number using UUID."""
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """Update grand total each time a line item is added, accounting for
        delivery costs."""
        self.order_total = (
            self.lineitems.aggregate(Sum("lineitem_total"))
            ["lineitem_total__sum"] or 0
        )

        # Get shipping settings or default to a value (for example, 50)
        shipping_settings = get_shipping_settings()
        default_shipping_cost = (
            50  # Default value if shipping settings are not available
        )

        # Fallback to default if settings are missing or improperly configured
        shipping_cost = getattr(
            shipping_settings, "standard_shipping_cost", default_shipping_cost
        )

        if self.order_total < shipping_cost:
            self.delivery_cost = self.order_total * shipping_cost / 100
        else:
            self.delivery_cost = 0

        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """Override the original save method to set the order number if it
        hasn't been set already."""
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    """Model to represent an order line item."""
    order = models.ForeignKey(
        Order,
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        related_name="lineitems",
    )
    product = models.ForeignKey(
        Microcontroller, null=False, blank=False, on_delete=models.CASCADE
    )
    product_size = models.CharField(
        max_length=2, null=True, blank=True
    )  # XS, S, M, L, XL
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, blank=False, editable=False
    )

    def save(self, *args, **kwargs):
        """Override the original save method to set the lineitem total and
        update the order total."""
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)
        self.order.update_total()  # Update the order total after saving

    def __str__(self):
        
        return f"SKU {self.product.sku} on order {self.order.order_number}"
    def __str__(self):
        """
        Returns a string representation of the OrderLineItem instance.

        Returns:
            str: A string in the format "SKU {product_sku} on order {order_number}",
                 where {product_sku} is the SKU of the product and {order_number}
                 is the order number associated with this line item.
        """
        return f"SKU {self.product.sku} on order {self.order.order_number}"

products/forms.py
from django import forms
from .models import Microcontroller


class MicrocontrollerForm(forms.ModelForm):
    delete_image = forms.BooleanField(required=False, 
                                      label="Delete existing image")

    class Meta:
        model = Microcontroller
        fields = [
            "sku",
            "name",
            "category",
            "bit_width",
            "cpu_architecture",
            "max_frequency_mhz",
            "ram_kb",
            "flash_memory_kb",
            "power_consumption_mw",
            "package_type",
            "description",
            "price",
            "rating",
            "image_url",
            "image",
            "delete_image",  # adaugă câmpul delete_image în fields
        ]
        widgets = {
            "sku": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter SKU"}
            ),
            "name": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Enter Microcontroller Name",
                }
            ),
            "category": forms.Select(attrs={"class": "form-control"}),
            # Use Select for bit_width as it now has choices
            "bit_width": forms.Select(attrs={"class": "form-control"}),
            # Use Select for cpu_architecture since it now has defined choices
            "cpu_architecture": forms.Select(attrs={"class": "form-control"}),
            "max_frequency_mhz": forms.NumberInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Enter Max Frequency (MHz)",
                }
            ),
            # Use Select for RAM size
            "ram_kb": forms.Select(attrs={"class": "form-control"}),
            # Use Select for Flash memory size
            "flash_memory_kb": forms.Select(attrs={"class": "form-control"}),
            "power_consumption_mw": forms.NumberInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Power Consumption in mW",
                }
            ),
            "package_type": forms.Select(attrs={"class": "form-control"}),
            "description": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": "Enter description",
                    "rows": 3,
                }
            ),
            "price": forms.NumberInput(
                attrs={"class": "form-control", "placeholder": "Enter Price"}
            ),
            "rating": forms.NumberInput(
                attrs={"class": "form-control", "placeholder": "Enter Rating"}
            ),
            "image_url": forms.URLInput(
                attrs={"class": "form-control",
                        "placeholder": "Enter Image URL"}
            ),
            "image": forms.FileInput(attrs={"class": "form-control"}),
        }

    def save(self, commit=True):
        instance = super().save(commit=False)

        # Șterge imaginea dacă delete_image este bifat
        if self.cleaned_data.get("delete_image") and instance.image:
            instance.image.delete()  # Șterge imaginea din stocare
            instance.image = None  # Setează câmpul imaginii pe None

        if commit:
            instance.save()
        return instance

    def clean_name(self):
        name = self.cleaned_data.get("name")
        if not name:
            raise forms.ValidationError("Microcontroller name is required.")
        return name

    def clean_price(self):
        price = self.cleaned_data.get("price")
        if price is not None and price < 0:
            raise forms.ValidationError("Price cannot be negative.")
        return price

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Microcontroller
from .forms import MicrocontrollerForm
from django.db.models.functions import Lower

from django.db.models import Q


def all_microcontrollers(request):
    """View to display all microcontrollers with optional sorting and search
    functionality."""
    microcontrollers = Microcontroller.objects.all()

    query = None
    selected_categories = None
    sort = None
    direction = None

    if request.GET:
        # Handle sorting
        if "sort" in request.GET:
            sortkey = request.GET["sort"]
            sort = sortkey
            if sortkey == "name":
                sortkey = "lower_name"
                microcontrollers = microcontrollers.annotate(
                    lower_name=Lower("name"))
            if sortkey == "category":
                sortkey = "category__name"
            if "direction" in request.GET:
                direction = request.GET["direction"]
                if direction == "desc":
                    sortkey = f"-{sortkey}"
            microcontrollers = microcontrollers.order_by(sortkey)

        # Handle category filtering
        if "category" in request.GET:
            selected_categories = request.GET["category"].split(",")
            print(selected_categories)
            microcontrollers = microcontrollers.filter(
                name__icontains=selected_categories[0]
            )

        # Handle search functionality
        if "q" in request.GET:
            query = request.GET["q"]
            if not query:
                messages.error(
                    request, "You didn't enter any search criteria!")
                return redirect(reverse("products"))

            queries = Q(name__icontains=query) | Q(
                description__icontains=query)
            microcontrollers = microcontrollers.filter(queries)

    current_sorting = f"{sort}_{direction}"

    context = {
        "microcontrollers": microcontrollers,
        "search_term": query,
        "current_categories": selected_categories,  
        "current_sorting": current_sorting,
    }
    return render(request, "products/microcontrollers.html", context)


# Display details of a single microcontroller


def microcontroller_detail(request, microcontroller_id):
    """View to display details of a specific microcontroller."""
    microcontroller = get_object_or_404(
        Microcontroller, pk=microcontroller_id)
    context = {
        "microcontroller": microcontroller,
    }
    return render(request, "products/microcontroller_detail.html", context)


# Add a new microcontroller


@login_required
def add_microcontroller(request):
    """View to add a new microcontroller to the system."""
    if not request.user.is_superuser:
        messages.error(request, "Sorry, only store owners can do that.")
        return redirect(reverse("home"))

    if request.method == "POST":
        microcontroller_form = MicrocontrollerForm(request.POST)

        if microcontroller_form.is_valid():
            microcontroller = microcontroller_form.save()
            messages.success(request, "Microcontroller successfully added!")
            return redirect(
                reverse("microcontroller_detail", args=[microcontroller.id])
            )
        else:
            messages.error(
                request,
                "Failed to add the microcontroller."
                 " Please ensure the form is valid.",
            )
    else:
        microcontroller_form = MicrocontrollerForm()

    context = {
        "form": microcontroller_form,
    }
    return render(request, "products/add_product.html", context)


# Edit an existing microcontroller


@login_required
def edit_microcontroller(request, microcontroller_id):
    """View to edit an existing microcontroller."""
    if not request.user.is_superuser:
        messages.error(request, "Sorry, only store owners can do that.")
        return redirect(reverse("home"))

    # Get the microcontroller object
    microcontroller = get_object_or_404(
        Microcontroller, pk=microcontroller_id)

    if request.method == "POST":
        microcontroller_form = MicrocontrollerForm(
            request.POST, request.FILES, instance=microcontroller
        )  # Include request.FILES to handle image upload
        if microcontroller_form.is_valid():
            microcontroller_form.save()
            messages.success(request,
                              "Microcontroller successfully updated!")
            return redirect(
                reverse("microcontroller_detail", args=[microcontroller.id])
            )
        else:
            messages.error(
                request,
                "Failed to update the microcontroller."
                 " Please ensure the form is valid.",
            )
    else:
        microcontroller_form = MicrocontrollerForm(instance=microcontroller)
        messages.info(request, f"You are editing {microcontroller.name}")

    context = {
        "microcontroller_form": microcontroller_form,
        "microcontroller": microcontroller,  # Ensure correct context
    }
    return render(request, "products/edit_microcontroller.html", context)


# Delete an existing microcontroller


@login_required
def delete_microcontroller(request, microcontroller_id):
    """View to delete a microcontroller from the system."""
    if not request.user.is_superuser:
        messages.error(request, "Sorry, only store owners can do that.")
        return redirect(reverse("home"))

    microcontroller = get_object_or_404(
        Microcontroller, pk=microcontroller_id)
    microcontroller.delete()
    messages.success(request, "Microcontroller deleted successfully!")
    return redirect(reverse("all_microcontrollers"))

# View to add features for a microcontroller

products/templates/products/add_microcontroller.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Microcontroller</title>
</head>
<body>
    <h1>Add New Microcontroller</h1>
    <form method="POST">
        {% csrf_token %}
        
        <h3>Microcontroller</h3>
        {{ microcontroller_form.as_p }}
        
        <h3>Manufacturer</h3>
        {{ manufacturer_form.as_p }}
        
        <h3>Peripheral</h3>
        {{ peripheral_form.as_p }}
        
        <h3>Features</h3>
        {{ features_form.as_p }}
        
        <button type="submit">Add Microcontroller</button>
    </form>
</body>
</html>

products/templates/products/microcontroller_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
                <div class="image-container my-5">
                    {% if microcontroller.image %}
                    <a href="{{ microcontroller.image.url }}" target="_blank">
                        <img class="card-img-top img-fluid" src="{{ microcontroller.image.url }}" alt="{{ microcontroller.name }}">
                    </a>
                {% elif microcontroller.image_url %}
                    <a href="{{ microcontroller.image_url }}" target="_blank">
                        <img class="card-img-top img-fluid" src="{{ microcontroller.image_url }}" alt="{{ microcontroller.name }}">
                    </a>
                {% else %}
                    <a href="">
                        <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ microcontroller.name }}">
                    </a>
                {% endif %}
                
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <div class="product-details-container mb-5 mt-md-5">
                    <p class="mb-0">{{ microcontroller.name }}</p>
                    <p class="lead mb-0 text-left font-weight-bold">${{ microcontroller.price }}</p>
                    {% if microcontroller.category %}
                    <p class="small mt-1 mb-0">
                        <a class="text-muted" href="{% url 'all_microcontrollers' %}?category={{ microcontroller.category.name }}">
                            <i class="fas fa-tag mr-1"></i>{{ microcontroller.category.friendly_name }}
                        </a>
                    </p>
                    {% endif %}
                    {% if microcontroller.rating %}
                        <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ microcontroller.rating }} / 5</small>
                    {% else %}
                        <small class="text-muted">No Rating</small>
                    {% endif %}
                    {% if request.user.is_superuser %}
                        <small class="ml-3">
                            <a href="{% url 'edit_microcontroller' microcontroller.id %}">Edit</a> | 
                            <a class="text-danger" href="{% url 'delete_microcontroller' microcontroller.id %}">Delete</a>
                        </small>
                    {% endif %}
                    <p class="mt-3">{{ microcontroller.description }}</p>
                    <form class="form" action="{% url 'add_to_bag' microcontroller.id %}" method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            {% with microcontroller.has_sizes as s %}
                            {% if s %}
                                <div class="col-12">
                                    <p><strong>Size:</strong></p>
                                    <select class="form-control rounded-0 w-50" name="product_size" id='id_product_size'>
                                        <option value="xs">XS</option>
                                        <option value="s">S</option>
                                        <option value="m" selected>M</option>
                                        <option value="l">L</option>
                                        <option value="xl">XL</option>
                                    </select>
                                </div>
                            {% endif %}
                            <div class="col-12">
                                <p class="mt-3"><strong>Quantity:</strong></p>
                                <div class="form-group w-50">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <button class="decrement-qty btn btn-black rounded-0" 
                                                data-item_id="{{ microcontroller.id }}" id="decrement-qty_{{ microcontroller.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-minus"></i>
                                                </span>
                                            </button>
                                        </div>
                                        <input class="form-control qty_input" type="number"
                                            name="quantity" value="1" min="1" max="99"
                                            data-item_id="{{ microcontroller.id }}"
                                            id="id_qty_{{ microcontroller.id }}">
                                        <div class="input-group-append">
                                            <button class="increment-qty btn btn-black rounded-0"
                                                data-item_id="{{ microcontroller.id }}" id="increment-qty_{{ microcontroller.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-plus"></i>
                                                </span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col{% if s %}-12 mt-2{% endif %}">
                                <a href="{% url 'all_microcontrollers' %}" class="btn btn-outline-black rounded-0 mt-5">
                                    <span class="icon">
                                        <i class="fas fa-chevron-left"></i>
                                    </span>
                                    <span class="text-uppercase">Keep Shopping</span>
                                </a>
                                <input type="submit" class="btn btn-black rounded-0 text-uppercase mt-5" value="Add to Bag">
                            </div>
                            <input type="hidden" name="redirect_url" value="{{ request.path }}">
                            {% endwith %}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
                <div class="image-container my-5">
                    {% if product.image %}
                        <a href="{{ product.image.url }}" target="_blank">
                            <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                        </a>
                        {% else %}
                        <a href="">
                            <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                        </a>
                    {% endif %}
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <div class="product-details-container mb-5 mt-md-5">
                    <p class="mb-0">{{ product.name }}</p>
                    <p class="lead mb-0 text-left font-weight-bold">${{ product.price }}</p>
                    {% if product.category %}
                    <p class="small mt-1 mb-0">
                        <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}">
                            <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                        </a>
                    </p>
                    {% endif %}
                    {% if product.rating %}
                        <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating }} / 5</small>
                    {% else %}
                        <small class="text-muted">No Rating</small>
                    {% endif %}
                    {% if request.user.is_superuser %}
                        <small class="ml-3">
                            <a href="{% url 'edit_product' product.id %}">Edit</a> | 
                            <a class="text-danger" href="{% url 'delete_product' product.id %}">Delete</a>
                        </small>
                    {% endif %}
                    <p class="mt-3">{{ product.description }}</p>
                    <form class="form" action="{% url 'add_to_bag' product.id %}" method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            {% with product.has_sizes as s %}
                            {% if s %}
                                <div class="col-12">
                                    <p><strong>Size:</strong></p>
                                    <select class="form-control rounded-0 w-50" name="product_size" id='id_product_size'>
                                        <option value="xs">XS</option>
                                        <option value="s">S</option>
                                        <option value="m" selected>M</option>
                                        <option value="l">L</option>
                                        <option value="xl">XL</option>
                                    </select>
                                </div>
                            {% endif %}
                            <div class="col-12">
                                <p class="mt-3"><strong>Quantity:</strong></p>
                                <div class="form-group w-50">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <button class="decrement-qty btn btn-black rounded-0" 
                                                data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-minus"></i>
                                                </span>
                                            </button>
                                        </div>
                                        <input class="form-control qty_input" type="number"
                                            name="quantity" value="1" min="1" max="99"
                                            data-item_id="{{ product.id }}"
                                            id="id_qty_{{ product.id }}">
                                        <div class="input-group-append">
                                            <button class="increment-qty btn btn-black rounded-0"
                                                data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-plus"></i>
                                                </span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col{% if s %}-12 mt-2{% endif %}">
                                <a href="{% url 'products' %}" class="btn btn-outline-black rounded-0 mt-5">
                                    <span class="icon">
                                        <i class="fas fa-chevron-left"></i>
                                    </span>
                                    <span class="text-uppercase">Keep Shopping</span>
                                </a>
                                <input type="submit" class="btn btn-black rounded-0 text-uppercase mt-5" value="Add to Bag">
                            </div>
                            <input type="hidden" name="redirect_url" value="{{ request.path }}">
                            {% endwith %}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}